name: Node

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@v6
      - run: pnpm i
      - run: pnpm pretest
      - run: pnpm test
